# Numpy - the numerical module of Python

### Numpy is the numerical module of Python. It’s a powerful N-dimensional array tool that is efficient for handling large datasets (e.g., images, high resolution spectra etc). In this demo we will learn how to use some of the basic numpy functions. If you want to get more fluent with numpy try the numpy tutorial:  https://numpy.org/devdocs/user/quickstart.html  

### The numerical package of Python. With it you can: 

- Make and manipulate sophisticated (broadcasting) arrays
- Read and work on (N-dimensional) data
- Do linear algebra, Fourier transformations, has random number capabilities

**Scipy** is the complimentary package. As a rule of thumb, if something is covered in a general textbook on numerical computing, it’s probably implemented in SciPy.


### Let's get started and see it in action:

### The most important thing always is to remember to start by importing numpy:

In [1]:
import numpy as np

### This imports the complete module numpy. The “as np” part is there to make typing more efficient for you: you now need to type only *np.function* when you want to call a function from numpy, rather than *numpy.function* . 
### Since later in the demo we will plot somethings as well, import the plotting module:


In [2]:
import matplotlib.pyplot  as plt   
## remember that if you knew --for some very weird case-- that you only need 1 or 2 packages you could just import
## those with: from matplotlib.pyplot import plot or (plot, xlabel, ylabel...)

### Let’s create our first numpy array. An array that starts at 1 and finishes at 100 with a step of 1:


In [2]:
x_numpy = np.arange( 1, 100, 1 ) 

In [3]:
y_numpy = np.arange(1, 100, 1)

In [4]:
print( type ( x_numpy ) )
print(y_numpy)
print( x_numpy )

<class 'numpy.ndarray'>
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48
 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71 72
 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95 96
 97 98 99]
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48
 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71 72
 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95 96
 97 98 99]


### To see the differences between numpy arrays and lists, and how efficient numpy is in numerical computing, let’s also create a list that is similar:


In [5]:
x_list = list( range(1, 100, 1) )
print(x_list)


[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99]


### Now let’s see the difference between the two when we want to multiple our arrays with a constant. 

### For the numpy array do : 

In [6]:
print( x_numpy * 10 )

[ 10  20  30  40  50  60  70  80  90 100 110 120 130 140 150 160 170 180
 190 200 210 220 230 240 250 260 270 280 290 300 310 320 330 340 350 360
 370 380 390 400 410 420 430 440 450 460 470 480 490 500 510 520 530 540
 550 560 570 580 590 600 610 620 630 640 650 660 670 680 690 700 710 720
 730 740 750 760 770 780 790 800 810 820 830 840 850 860 870 880 890 900
 910 920 930 940 950 960 970 980 990]


### If you try the same for the list:  x_list * 10  what do you get?

In [7]:
print( x_list * 10 )

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59

### Lists are not arrays. To do numerical computations with their elements we need to call them one by one. 
You need a for loop or this: [i*10 for i in x_list] and you will get the same results as with x_numpy * 10. 


In [8]:
for i in range(len(x_list)):
    print( x_list[i] * 10 )
    
#or simpler: [i*10 for i in x_list]   # ---> "list comprehension" see later class

10
20
30
40
50
60
70
80
90
100
110
120
130
140
150
160
170
180
190
200
210
220
230
240
250
260
270
280
290
300
310
320
330
340
350
360
370
380
390
400
410
420
430
440
450
460
470
480
490
500
510
520
530
540
550
560
570
580
590
600
610
620
630
640
650
660
670
680
690
700
710
720
730
740
750
760
770
780
790
800
810
820
830
840
850
860
870
880
890
900
910
920
930
940
950
960
970
980
990


### What happens though, when we have a *large* array we want to work with? Let’s make a new array that goes from 1 to 1,000,000 with a step of 1:


In [9]:
%%timeit
x_numpy_new = np.arange(1, 240000, 1)   ### note I keep this one small....try pushing it to 1,000,000 and see the
                                        ### difference even more obv 

287 µs ± 19.7 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


### and a similar new list:


In [11]:
%%timeit
x_list_new = list( range( 1, 240000, 1) )

11.1 ms ± 437 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


### Now let’s calculate the square of our new array:


In [12]:
y_numpy = x_numpy **2 
print( x_numpy, y_numpy)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48
 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71 72
 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95 96
 97 98 99] [   1    4    9   16   25   36   49   64   81  100  121  144  169  196
  225  256  289  324  361  400  441  484  529  576  625  676  729  784
  841  900  961 1024 1089 1156 1225 1296 1369 1444 1521 1600 1681 1764
 1849 1936 2025 2116 2209 2304 2401 2500 2601 2704 2809 2916 3025 3136
 3249 3364 3481 3600 3721 3844 3969 4096 4225 4356 4489 4624 4761 4900
 5041 5184 5329 5476 5625 5776 5929 6084 6241 6400 6561 6724 6889 7056
 7225 7396 7569 7744 7921 8100 8281 8464 8649 8836 9025 9216 9409 9604
 9801]


### works nice and fast...let's do the same for the list:

In [13]:
y_list = [i**2 for i in x_list]
#print(y_list)

In [14]:
print( y_list )

[1, 4, 9, 16, 25, 36, 49, 64, 81, 100, 121, 144, 169, 196, 225, 256, 289, 324, 361, 400, 441, 484, 529, 576, 625, 676, 729, 784, 841, 900, 961, 1024, 1089, 1156, 1225, 1296, 1369, 1444, 1521, 1600, 1681, 1764, 1849, 1936, 2025, 2116, 2209, 2304, 2401, 2500, 2601, 2704, 2809, 2916, 3025, 3136, 3249, 3364, 3481, 3600, 3721, 3844, 3969, 4096, 4225, 4356, 4489, 4624, 4761, 4900, 5041, 5184, 5329, 5476, 5625, 5776, 5929, 6084, 6241, 6400, 6561, 6724, 6889, 7056, 7225, 7396, 7569, 7744, 7921, 8100, 8281, 8464, 8649, 8836, 9025, 9216, 9409, 9604, 9801]


### As you might have noticed, it takes (much) longer to do this with a list than with numpy! (for 1,000,000 it's a factor of 20 or more)


### another example of the power of numpy (and of tricky bugs): 
<img src="bug_np.png" width=600 height=600 />


In [15]:
# let's test what this person does in the start (since we imported numpy we 'll use np.cos):
wj0 = []
N1 = 5000

In [16]:
print( wj0)

[]


In [17]:
for i in range( 0, N1 ):   ## create a range 0 to N1. Then for every element in the range scan it 1 by 1 and assign
                           ## that value to i
    w = 0.5 * ( 1 - np.cos( 2 * np.pi * i / N1 ) )  ## use this value to make a cos function of i 
    wj0.append( w )        ## append it to the end of the list to make your list

In [18]:
## takes some time and gives:
print( wj0 )

[0.0, 3.9478412411364516e-07, 1.57913587295333e-06, 3.5530533763483696e-06, 6.316533517125578e-06, 9.869571931442334e-06, 1.4212163008509027e-05, 1.9344299890866612e-05, 2.5265974474109054e-05, 3.197717740710537e-05, 3.947789809194413e-05, 4.7768124683988944e-05, 5.6847844091822974e-05, 6.671704197735995e-05, 7.737570275573313e-05, 8.882380959551739e-05, 0.00010106134441850712, 0.00011408828790010483, 0.0001279046194688771, 0.00014251031730694308, 0.00015790535835003006, 0.00017408971828714037, 0.0001910633715609955, 0.00020882629136786957, 0.00022737844965775578, 0.0002467198171342, 0.0002668503632545782, 0.00028777005622998564, 0.00030947886302540306, 0.000331976749359586, 0.00035526367970539763, 0.00037933961728953136, 0.0004042045240927883, 0.00042985836085013274, 0.00045630108705063677, 0.0004835326609376467, 0.0005115530395087275, 0.0005403621785159407, 0.0005699600324657328, 0.0006003465546189912, 0.0006315216969912663, 0.000663485410352771, 0.0006962376442284368, 0.000729778346

In [19]:
# now let's numpy it:
n = np.arange(0, N1, 1)

# instead of looping over i we create an array of all the x-variables :
# and then we make the numpy cos array:

wj02 = 0.5 * ( 1 - np.cos( 2 * np.pi * n / N1 ) )



In [20]:
# done in a fraction of the time that the appending to list needed....if you for whatever 
# reason *needed* a list you can always list() it:

print( wj02 )

[0.00000000e+00 3.94784124e-07 1.57913587e-06 ... 3.55305338e-06
 1.57913587e-06 3.94784124e-07]


In [21]:
#what types are they?

### Let’s create an array of 10 elements that are all 0:

In [31]:
x = np.zeros((10,10))
print( x )

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


### and an array of 10 elements that are all 1:

In [32]:
y = np.ones( 10)
print( y )

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


### Let’s do some math with them:

In [24]:
print ( x + y )
print ( x - y ) 
print ( x + 5 )
print ( x * y ) 


[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]
[[-1. -1. -1. -1. -1. -1. -1. -1. -1. -1.]
 [-1. -1. -1. -1. -1. -1. -1. -1. -1. -1.]
 [-1. -1. -1. -1. -1. -1. -1. -1. -1. -1.]
 [-1. -1. -1. -1. -1. -1. -1. -1. -1. -1.]
 [-1. -1. -1. -1. -1. -1. -1. -1. -1. -1.]
 [-1. -1. -1. -1. -1. -1. -1. -1. -1. -1.]
 [-1. -1. -1. -1. -1. -1. -1. -1. -1. -1.]
 [-1. -1. -1. -1. -1. -1. -1. -1. -1. -1.]
 [-1. -1. -1. -1. -1. -1. -1. -1. -1. -1.]
 [-1. -1. -1. -1. -1. -1. -1. -1. -1. -1.]]
[[5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]
 [5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]
 [5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]
 [5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]
 [5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]
 [5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]
 [5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]
 [5. 5.

### How does numpy treat these arrays for the numerical calculations?  

### Now let’s create a 2x2 array of zeros:

In [25]:
z = np.zeros( ( 2 , 2 ) )  #---> note the extra ( ) to show it's a 2d array
print( z )

[[0. 0.]
 [0. 0.]]


### You can check the shape of your array out with: .shape

In [33]:
print(z.shape)


(2, 2)


In [34]:
print( z + 5 )

[[5. 5.]
 [5. 5.]]


In [35]:
print(z[1,1])

0.0


### and try to multiply it with x.  What happens? Why doesn’t it work?


In [29]:
z * x 

ValueError: operands could not be broadcast together with shapes (2,2) (10,10) 

### Let’s now change z to be a 10x2 array of ones: 

In [24]:
z = np.ones( ( 10 , 2 ) )

### try z \* x and x \* z. 


In [25]:
z * x

array([[0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.]])

In [26]:
x * z 

array([[0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.]])

### Why don’t they work? 


In [27]:
# try:

a1 = np.array( [ [1 , 2 , 3] , [4 , 5 , 6] , [7 , 8 , 9] ] )
b1 = np.ones( ( 3 , 3 ) )

print( a1 )
print( b1 )


[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [28]:
print( a1 * b1 )

[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]


### how does “ \* ” work?

In [29]:
print( np.matmul(a1,b1))

[[ 6.  6.  6.]
 [15. 15. 15.]
 [24. 24. 24.]]


### “ \* ” does element by element multiplication, not matrix multiplication. The different dimensions of your x and z arrays means that * cannot operate as it should. Python gives an error message to warn you that you try something “illegal”. 

#### What we need since we have two matrices with different dimensions is np.matmul(x,z) . This will give us a (1,2) x (10,2) => (1,2) array, as it should!


In [30]:
x = np.arange(0, 2 )

print ( np.matmul ( x, z ) )

ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 10 is different from 2)

In [31]:
print ( np.matmul ( a1, b1 ) )

[[ 6.  6.  6.]
 [15. 15. 15.]
 [24. 24. 24.]]


### A feature of Python is “broadcasting”. When some conditions are met, Python will allow you to multiply arrays that have different dimensions. The smaller array is broadcast across the larger array so that they have compatible shapes. For example, create an array 


In [32]:
z_2 = np.array( [ 5 ] )

### and add it to your array z.  Following the strict rules of math this should not work! However, Python allows you to do this using broadcasting:

In [20]:
print( z_2 + z )

NameError: name 'z' is not defined

###  What it does is it ‘creates’ a (2,2) array of 5s and adds it to your array z following the element-by-element rules of matrix addition (same for multiplication etc). 


### Let’s create an array q that goes from 0 to 100 with a step of 0.1, and a q_cos that is the cosine of q:


In [21]:
q     = np.arange( 0, 100, 0.1 )
q_cos = np.cos( q )

### and and array q_sin that is the sine of q:


In [22]:
q_sin = np.sin( q )

### Let’s plot q_cos and q_sin as a function of q :

In [23]:
plt.figure( figsize = ( 6, 6 )  )
plt.plot( q, q_cos, '--',color= 'b') 
plt.plot( q, q_sin, '--',color= 'g')


NameError: name 'plt' is not defined

#### This is a lot of information. Let’s only focus on what happens from q[0] to q[100] :


In [ ]:
plt.figure( figsize = ( 12, 10 )  )
plt.plot( q [ 0 :  101 ] , q_cos [ 0 :  101 ] , color= 'red'  ) 
plt.plot( q [ 0 :  101 ] , q_sin [ 0 :  101 ] , color= 'blue' )


### Better! As you can see we can *slice* a numpy array. 

### Let’s try some more slicing. 


In [60]:
z = np.arange( 1,20 )
print(z)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


In [65]:
#### Let's try the following:

print(np.where(z==5))

(array([4], dtype=int64),)


In [37]:
# print the z first:

print(z)


[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


In [38]:
# print z till 10 and z from element 2 to 5
 
print(z[:10])
print(z[2:5])

[ 1  2  3  4  5  6  7  8  9 10]
[3 4 5]


In [39]:
# print all elements from 6 onwards:
print(z[6:])

[ 7  8  9 10 11 12 13 14 15 16 17 18 19]


In [40]:
# print z from 12 to 2 with a -2 step; print z from 10 to end with step of 2

print( z[12:2:-2] )

print( z[10::2] )

[13 11  9  7  5]
[11 13 15 17 19]


### Let’s now assign a value of 40 to z[4] and of 42 to z[11:13]. Does it work?

In [41]:
z[4] = 40

z[11:13] = 42

print(z)


[ 1  2  3  4 40  6  7  8  9 10 11 42 42 14 15 16 17 18 19]


### Print all values of z that are larger than 10 :

In [42]:
print(z > 10)

[False False False False  True False False False False False  True  True
  True  True  True  True  True  True  True]


In [43]:
print(z[z > 10])

[40 11 42 42 14 15 16 17 18 19]


### now print all  values that are smaller than 3 :

In [48]:
print(z[np.where(z>2)])
print(z[np.where(z>2)])

[ 3  4 40  6  7  8  9 10 11 42 42 14 15 16 17 18 19]
[ 3  4 40  6  7  8  9 10 11 42 42 14 15 16 17 18 19]


In [49]:
print(z[3 > z])

[1 2]


### what does z<3 alone give you?


In [50]:
print( z < 3 )


[ True  True False False False False False False False False False False
 False False False False False False False]


### now what if you want to have multiple conditions? 

In [51]:
print( z [ ( z > 10 ) & ( z < 15 ) ] )   # ---> mask for data that both z > 10 and z < 15

print(z[(z>10) & (z<15)])

[11 14]
[11 14]


### also, if you want to know *where* (which elements of) an array meet a specific criterion use the numpy where statement:


In [65]:
print( np.where ( z < 14 ) )


(array([0, 0, 1, 1, 2, 2, 3, 3, 5, 5, 6, 6, 7, 7, 8, 8, 9, 9], dtype=int64), array([0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1], dtype=int64))


In [58]:
print( z[ np.where ( z == 14 ) ] )

[14]


In [53]:
plt.figure( figsize = ( 6, 6 )  )
plt.plot( q  , q_cos  , color= 'red'  ) 
plt.plot( q  , q_sin  , color= 'blue' )
plt.ylim( 0, 1.01)

NameError: name 'plt' is not defined

### Then let’s plot all parts of q_cos and q_sin that are larger than 0:

In [ ]:
plt.figure( figsize = ( 6, 6 ) )

plt.plot( q [ np.where( q_cos > 0 ) ], q_cos[ np.where( q_cos > 0 ) ],    
         color = 'red' )
plt.plot( q [ np.where( q_sin > 0 ) ], q_sin[ np.where( q_sin > 0 ) ], 
         color = 'blue', linestyle = 'none', marker = 'o')
plt.xlim(0,10) 

In [ ]:
### of course you might have noticed that you don't even need the np.where at all here ;)  


In [ ]:
plt.figure( figsize = ( 6,6 ) )

plt.plot( q    [  q_cos > 0  ],  
          q_cos[  q_cos > 0    ], color='red')
plt.plot( q    [  q_sin > 0  ],  
          q_sin[  q_sin > 0  ], color='blue')
plt.xlim(0,10) 

In [ ]:
## why? q_cos > 0 gives True False:
#print( q_cos > 0)
# so q [  q_cos > 0  ] will give you only the ones where it is True, i.e., you have already filtered it:
#test1 = q [  q_cos > 0  ]
#print ( test1 [ 10 : 20 ] )
#print ( q [ 10 : 20 ] )

### you can also mask in 2-dimensions:



In [54]:
tst1 = np.array( [ [ 1, 1, 1 ], [ 2, -2, 2 ], [ -4, -4, 4 ] ] )
tst2 = np.array( [ [ 1, 1, 1 ], [ 2, -2, 2 ], [ -3, 3, 3 ] ] )

In [55]:
print(tst1)
print(tst2)

[[ 1  1  1]
 [ 2 -2  2]
 [-4 -4  4]]
[[ 1  1  1]
 [ 2 -2  2]
 [-3  3  3]]


In [ ]:
q = tst1[ np.where( ( tst1 < 0 ) & ( tst2 < 0 ) )  ] 

In [ ]:
print( q )

In [ ]:
np.where( ( tst1 < 0 ) & ( tst2 < 0 ) )

In [ ]:
np.where(  tst1 < 0 )

### can you see how we can add the x-axis < 6 and >1  in the q [defined_limits]  command?

In [ ]:
plt.figure( figsize = ( 6, 6 ) )

plt.plot( q    [ (q_cos<0) & (q>1) & (q<6) ],  
          q_cos[ (q_cos<0) & (q>1) & (q<6)  ], color='red')

plt.plot( q    [ (q_sin<0) & (q>1) & (q<6)  ],  
          q_sin[(q_sin<0) & (q>1) & (q<6) ], color='blue')

### i.e., you can use the >, <, where statements as a mask, to only show/ work with data that satisfy a specific criterion in any dimensions you want


### some more where cases:

In [56]:
test_1 = np.arange(0,9).reshape((3, 3))

In [57]:
print( test_1 )

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [72]:
# make variable test_2 that is 4 times all elements of test_1, where test_1 is less than 4:
test_2 = (test_1[test_1 <4])*4

In [73]:
print( test_2 )

[ 0  4  8 12]


In [74]:
print(  test_1 [ np.where( test_1 < 4 ) ] * 4)

[ 0  4  8 12]


In [ ]:
#  can also use masks with x, y condition and return different array:
a = np.array( [[0, 1, 2],
               [0, 2, 4],
               [0, 3, 6] ] )

In [ ]:
print ( a )
print ( np.where( a < 4, a, -1 ) ) # -1 is broadcast   

###Printing what is less than 4 but if its not it prints -1

In [ ]:
b = np.array( [[0, 1, 2],
               [3, 4, 5],
               [7, 8, 9] ] )

In [ ]:
print ( np.where(a > 4, -1 , b * 10 ) ) # -1 is broadcast 

In [ ]:
# same with: 
#a = np.arange(10)

In [ ]:
#print( a )
#print( np.where(a < 5, -3 , a) )


### note for the end: you can also slice 2D or ND arrays :

In [83]:
#e.g., 

my_2d_array = np.array(  [ [ 1, 2, 3, 4, 5 ],
                          [ 12 , 15, 16, 22,  18 ], 
                          [ 42, 54, 53, 67, 88 ] , 
                          [ -41, 36, 98, 10, 12 ]  ] )


In [84]:
print( my_2d_array)

[[  1   2   3   4   5]
 [ 12  15  16  22  18]
 [ 42  54  53  67  88]
 [-41  36  98  10  12]]


In [85]:
# how do I get " 53 " ?

In [86]:
print( my_2d_array [ 2 , 2] )

53


In [87]:
# how do I get the slice:  16 22 53 67 ?
print( my_2d_array[ 1 , 2 : 4 ] , my_2d_array[2 , 2 : 4] )

[16 22] [53 67]


In [88]:
print( my_2d_array[1,2])
print( my_2d_array[1,3])
print( my_2d_array[2,2])
print( my_2d_array[2,3])

16
22
53
67


In [91]:
a = np.array( [ 1, 2, 3, 4] )
print(type(a))
print(np.where( a > 2 ))

<class 'numpy.ndarray'>
(array([2, 3], dtype=int64),)


In [92]:
a = np.array([[0, 1, 2],
              [0, 6, 4],
              [0, 3, 6]])
print(a)

[[0 1 2]
 [0 6 4]
 [0 3 6]]


In [97]:
print( np.where( a > 2 ) )


(array([1, 1, 2, 2], dtype=int64), array([1, 2, 1, 2], dtype=int64))


In [96]:
print(a[ np.where( a > 2 ) ])

[6 4 3 6]
