In [1]:
import numpy as np

# FOR == repetitive tasks
# IF     == conditional tasks

<img src="for_loop_flowchart.png" width=600 height=500 />


## 1. For - if : practical examples with text, numpy arrays and dictionaries

### What colors is a rainbow made of? Make a list ***rainbow_colors*** that has the names of the rainbow colors. Print an informative statement that the colors of the rainbow are....and print them in order from top (outside of the circle) to bottom. How about a secondary rainbow?

In [3]:
rainbow_colors = [ 'red', 'orange', 'yellow', 'green', 'blue', 'indigo', 'violet' ]

In [6]:
print('The colors of the rainbow are: \n')

for name in rainbow_colors:
    print(name)

The colors of the rainbow are: 

red
orange
yellow
green
blue
indigo
violet


In [14]:
for name in range(len(rainbow_colors)):
    print(rainbow_colors[(len(rainbow_colors)-1)-name])

violet
indigo
blue
green
yellow
orange
red


### Now let's put a for/if in practice with numbers. Make a for loop that will go through numbers 1 to 30 (including 30) and print them out. When it reaches 10, 20 and 30 it will print a blank space.

In [15]:
nums = np.arange(1,31)

In [16]:
for i in nums:
    print(i)
    if (i == 10) or (i == 20) or (i==30):
        print('       ')

1
2
3
4
5
6
7
8
9
10
       
11
12
13
14
15
16
17
18
19
20
       
21
22
23
24
25
26
27
28
29
30
       


### Solving a Sudoku
<img src="sudoku.png" width=300 height=300 />
source: Reader's Digest

### How do you solve it? Use FOR and IF to describe the process.¶

### Teach a computer to read! 

<img src="reading_directions.png" width=600 height=500 />

<img src="write_1.png" width=250 height=250 />
<img src="write_2.png" width=300 height=250 />

<img src="write_3.png" width=100 height=70 />

### Write 2-3 sentences about the process you do to read a text in Western languages.  Use FOR and IF to describe the process. 

### put your ideas in practice: Open file abstract_from_emma.txt and read it in variable ***abstract***. Then, use a for/ if to print out the text letter by letter. When there is a new line ask the code to print a --- or 'new line'  to show that it understands you are in a new line. 

In [1]:
# and now, use a nested for loop: loop over the lines, then for every line: split it in the words it's made of
# and print the words out one after another. If there is is new line print the ------ again.


### Now we need to read a text that is written the other way around. Assuming we told the computer that it needs to read backwards read the file ***back_forth_reading.txt*** into variable ***new_text***.  Print it out so that we can read it (letter by letter, or word by word are both fine). 

- Discuss:
    1. How would we let the computer know it needs to read the other way around?
    2. How would you code it to read the text and print it in a way that you understand?

### For advertising reasons you need to figure out what the favor color of a car is. You get data with the color of different cars passing through a given intersection on a typical day.  How many cars of red color and how many black ones are on the street on a typical day?  How can you calculate it w/o using a build-in function?

### How could you do it faster?

In [17]:
typical_day = [ 'white','green', 'black','red', 'blue','white','white','red',
               'blue','blue','red','white', 'red','black','green','white','white',
               'white','white','white','blue','blue', 'red','black','green','red',
               'white','blue', 'red','black','red','blue','blue','blue', 'black',
               'green','black','green','green']

In [18]:
#check if there is no car of a given color; print statement if that is the case

In [20]:
red_count = 0

black_count = 0


for car in typical_day:
    if car == 'black':
        black_count = black_count+1
    if car == 'red':
        red_count = red_count+1
        
print(red_count,black_count)

8 6


In [3]:
#print informative statement.

In [4]:
#how else would you do it?

In [22]:
print(typical_day.count('red'))
print(typical_day.count('black'))

8
6


### Use numpy to read-in the ***small_dataset.dat*** in a variable ***data***. Calculate the sum of each line (assign them to variable sum1, sum2 and sum3) with a for loop . If a total is larger than 500 print a warning text.

### Use another for loop to get the sum of each column (csum1, csum2, csum3). Give a warning when the total is larger than 700.

### I have a dictionary of names of students and a list of their average grades. Scan through the names and print a letter grade for every student (assume plain ABC with A if grade is >0.90 ; B if grade 0.90> n > 0.80 and C if grade < 0.80)

In [66]:
classroom = { 'Jane': 0.92 , 'Joe': 0.85, 'Petra': 0.78, 'Peter': 0.81 }

### Make a function ***min_max_words*** that gets as input any string, splits it in the words it is made of and returns a tuple with the shortest and longest word. Call it for the sentence: "If you are trying to come up with a new concept, a new idea or a new product, a random sentence may help you find unique qualities you may not have considered"

In [29]:
def min_max_word(string):
    """Splits words and returns a tuple with the shortest and longest word"""
    
    q = string.split()
    
    smallest_word = q[0]
    longest_word = q[0]
    
    for word in q:
        if len(word) > len(longest_word):
            longest_word = word
        if len(word) < len(smallest_word):
            smallest_word = word
            
    return ( smallest_word , longest_word )

In [30]:
my_sentence = """If you are trying to come up with a new concept, a new idea or a 
        new product, a random sentence may help you find unique qualities you may not have considered"""

In [31]:
print(min_max_word(my_sentence))

('a', 'considered')


## Slices (and some more for/ifs)

In [32]:
my_data = np.arange( 1, 26 ).reshape( (5, 5) )

In [33]:
print( my_data )

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]


### Access and print the numbers from 6 up to (including) 10

In [36]:
print(my_data[ 1:2, 0:])

[[ 6  7  8  9 10]]


### Access and print the numbers 4 9 14 19 24

In [38]:
print(my_data[ 0 : ,  3 ])

[ 4  9 14 19 24]


### Access and print the numbers 3 8 4 9 and number 14

In [39]:
print(my_data[ 2 , 3])

14


### Scan ***my_data*** with a for/if and find the minimum:

In [43]:
print(my_data.min())
print(my_data.max())
print(my_data.mean())

1
25
13.0


In [5]:
#why wouldn't you do this? what is better to do?


### Calculate the mean of the ***my_data*** table w/o using numpy.

### You have a list with the names of numbers. Slice it to access the names of 3 and 5.

In [80]:
list_of_names = [ 'One', 'Two', 'Three', 'Four', 'Five', 'Six' ]

### Let's make boxes with sides x, y, z and calculate their volume. Create array x that is a range from 0.1 to 10 with a step of 0.2. Make array y that is a linspace from 0.1 to 10 in 50 steps. Then make array z that is equal to $x^2 + y^{0.3}$. Calculate the volume of the boxes [assume it is in cu ft ] with every possible combinations of x, y, z. What is the maximum, minimum and mean volume of our boxes in ? If I need boxes with a volume more than 8000 cu ft, how many boxes will I have?